---
- name: Install packages needed for Docker
  apt:
    name:
      - docker.io
      - ca-certificates
      - curl
      - apt-transport-https
      - software-properties-common
      - gnupg2
    state: latest

- name: Add an APT Repository Key for Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add an APT Repository for the Key of Docker
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu focal stable"
    state: present

- name: Install the Docker
  apt:
    name: docker
    state: latest

- name: Start the Docker Service 
  service:
    name: docker
    state: started
    enabled: true

- name: Ensure group docker exists
  group:
    name: docker
    state: present

- name: Adding the current user to the docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
- name: Creating a directory for Dockerfile
  file:
    path: /home/micoflores/docker_config
    state: directory

- name: Copying the Dockerfile
  copy:
    src: /home/micoflores/Flores_HOA11/roles/Docker/dockerfile
    dest: /home/micoflores/docker_config
    owner: micoflores
    group: micoflores

- name: Creating volume
  file:
    path: /home/micoflores/pages
    state: directory

- name: Building image
  community.docker.docker_image:
    name: lamp-userver
    tag: 1.0
    build:
      path: /home/micoflores/docker_config
    source: build

- name: Deploying container
  community.docker.docker_container:
    name: lamp-userver
    image: lamp-userver:1.0
    state: started
    exposed_ports:
      - "80"
    ports:
      - "8080:80"
    volumes:
      - /home/micoflores/pages:/var/www/html

- block:
  - name: Verify if lamp-userver container is running
    shell: docker ps
    register: container_status


